// AUTO-GENERATED by scripts/generate-media.mjs — do not edit by hand.
// Re-run `bun run optimize` to regenerate from public/images + public/videos.

export type Category = "portraits" | "weddings" | "events" | "sports";

export interface Photo {
  slug: string;
  src: string;
  avif: string;
  webp: string;
  width: number;
  height: number;
  orientation: "landscape" | "portrait";
  blurDataURL: string;
  alt: string;
  category: Category;
  featured: boolean;
  original: string;
}

export interface VideoClip {
  slug: string;
  title: string;
  clip: string;
  poster: string;
  width: number;
  height: number;
  orientation: "landscape" | "portrait";
  original: string;
}

export const categories: { id: Category; label: string }[] = [
  { id: "portraits", label: "Portraits" },
  { id: "weddings", label: "Weddings" },
  { id: "events", label: "Events" },
  { id: "sports", label: "Sports" },
];

export const photos: Photo[] = [
  {
    "slug": "anselm-0093",
    "src": "/gallery/anselm-0093.jpg",
    "avif": "/gallery/anselm-0093.avif",
    "webp": "/gallery/anselm-0093.webp",
    "width": 2179,
    "height": 3269,
    "orientation": "portrait",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAeABQDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAIFBAP/xAAlEAACAgIBBAAHAAAAAAAAAAABAgMRAAQxBRIhQRMiUWKR0fD/xAAWAQEBAQAAAAAAAAAAAAAAAAABAgD/xAAWEQEBAQAAAAAAAAAAAAAAAAAAARH/2gAMAwEAAhEDEQA/AFk66s2wsMcRYFktr5K+6/uM4dR6uJZRHCoESP323JPu8hiKSzZIPH0zvDpSyqaZfAPPvNQ3xbsSKVZ5Ks9vaPFYZMWJgOR5www6pWrsvJI484yvIm/poPEcjU9DnFRViUStbfb6zTryvu7SiMInYPlYiyBd/nC1cilJB0hGqTRfur0D+8My7W1Bqy/CMLTMB5d3Nk4ZE1Vx/9k=",
    "alt": "Anselm 0093",
    "original": "ANSELM-0093.jpg",
    "category": "portraits",
    "featured": false
  },
  {
    "slug": "anselm-0440",
    "src": "/gallery/anselm-0440.jpg",
    "avif": "/gallery/anselm-0440.avif",
    "webp": "/gallery/anselm-0440.webp",
    "width": 2560,
    "height": 1707,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAGAAAAgMAAAAAAAAAAAAAAAAAAAUDBAb/xAAgEAEAAgICAQUAAAAAAAAAAAABAgMAEQQSUSEyYWJy/8QAFwEAAwEAAAAAAAAAAAAAAAAAAAEDBP/EABoRAAICAwAAAAAAAAAAAAAAAAABAgQUMVH/2gAMAwEAAhEDEQA/AGFnErrN2MYH2dZUkcVl1L4D5U1maOQylKUma/M3JKYRuQWYrr3uWVmS2jK6cJaH7xYrssgn6MMQ9KY+kq2T57JhjynwMGPT/9k=",
    "alt": "Anselm 0440",
    "original": "ANSELM-0440.jpg",
    "category": "portraits",
    "featured": true
  },
  {
    "slug": "anselm-0667",
    "src": "/gallery/anselm-0667.jpg",
    "avif": "/gallery/anselm-0667.avif",
    "webp": "/gallery/anselm-0667.webp",
    "width": 2560,
    "height": 1707,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAMEAgX/xAAhEAEAAQQBBAMAAAAAAAAAAAABAgADBBEhEhMxQUJRkf/EABcBAAMBAAAAAAAAAAAAAAAAAAACAwT/xAAYEQACAwAAAAAAAAAAAAAAAAAAAQISFP/aAAwDAQACEQMRAD8A5NvLWJzTO7clFkEkPLWMdjbx7YW476Hb7Xfn8prkzFj8V5PuoVRu0yJp5EoySWxPTRUM5LJd0U1EGiR//9k=",
    "alt": "Anselm 0667",
    "original": "ANSELM-0667.jpg",
    "category": "portraits",
    "featured": false
  },
  {
    "slug": "anselm-0673",
    "src": "/gallery/anselm-0673.jpg",
    "avif": "/gallery/anselm-0673.avif",
    "webp": "/gallery/anselm-0673.webp",
    "width": 2560,
    "height": 1707,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAIDBv/EACEQAAEEAgEFAQAAAAAAAAAAAAEAAgMRBCESBSIjMVGS/8QAFgEBAQEAAAAAAAAAAAAAAAAAAQAC/8QAFREBAQAAAAAAAAAAAAAAAAAAACH/2gAMAwEAAhEDEQA/AMrDgzzsL4oy8D4nHTck14yL9K+BkOjxncSe2zo1e1A503Cg6t2itQhwng1yZ+kKJe4mzsoUH//Z",
    "alt": "Anselm 0673",
    "original": "ANSELM-0673.jpg",
    "category": "portraits",
    "featured": true
  },
  {
    "slug": "anselm-3912",
    "src": "/gallery/anselm-3912.jpg",
    "avif": "/gallery/anselm-3912.avif",
    "webp": "/gallery/anselm-3912.webp",
    "width": 2560,
    "height": 1709,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAGAAAAgMAAAAAAAAAAAAAAAAAAAIDBAb/xAAiEAACAgIBAwUAAAAAAAAAAAABAgADERIEBRUhIjEzQWH/xAAVAQEBAAAAAAAAAAAAAAAAAAACAf/EABgRAAMBAQAAAAAAAAAAAAAAAAABEhFB/9oADAMBAAIRAxEAPwDI1UW3fGhbzjxJl6fyPd62CgZJ/IJzr69PUrBBqoZAcCIOXapOpAz9AQOhKejCirJDMVIOCNhCXeH0/uFRvawIdiMBISULD//Z",
    "alt": "Anselm 3912",
    "original": "ANSELM-3912.jpg",
    "category": "portraits",
    "featured": false
  },
  {
    "slug": "andi-11",
    "src": "/gallery/andi-11.jpg",
    "avif": "/gallery/andi-11.avif",
    "webp": "/gallery/andi-11.webp",
    "width": 2560,
    "height": 1707,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAMEBf/EACYQAAIBAwIEBwAAAAAAAAAAAAECEQADIQQTBRIiMSMyQWGBkaL/xAAWAQEBAQAAAAAAAAAAAAAAAAACAAH/xAAYEQEAAwEAAAAAAAAAAAAAAAAAAREhMf/aAAwDAQACEQMRAD8AhV7YUmykTmUMfo5+hT7ugbw7aMql1JPKwBc+ue9M4fNy7tsQyKswygzmKZrnDcRVUU2+shuU+bE/FHSjlsZ9OqNGwx9yRRUWsa4dVcG42GI70Vay5f/Z",
    "alt": "Andi 11",
    "original": "Andi-11.jpg",
    "category": "portraits",
    "featured": false
  },
  {
    "slug": "andi-13",
    "src": "/gallery/andi-13.jpg",
    "avif": "/gallery/andi-13.avif",
    "webp": "/gallery/andi-13.webp",
    "width": 2560,
    "height": 1707,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAMEBf/EACMQAAIBBAEDBQAAAAAAAAAAAAECAAMEESESImFxI0FRkfD/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAv/EABcRAQEBAQAAAAAAAAAAAAAAAAABEQL/2gAMAwEAAhEDEQA/AJrdkQhXRSWbinbcut7imxqqqZClsgHGwOxmVRIZCWXJQBgfnz+9peHVCjLTXrXkR5xCpNOUVKqh6NNwpGwWJ39QiBcBET0UORnZMI0vL//Z",
    "alt": "Andi 13",
    "original": "Andi-13.jpg",
    "category": "portraits",
    "featured": true
  },
  {
    "slug": "copy-of-dscf0630",
    "src": "/gallery/copy-of-dscf0630.jpg",
    "avif": "/gallery/copy-of-dscf0630.avif",
    "webp": "/gallery/copy-of-dscf0630.webp",
    "width": 2560,
    "height": 1707,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAUGAwT/xAAgEAABBQACAgMAAAAAAAAAAAABAAIDESEEBRIUYcHR/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgP/xAAXEQEAAwAAAAAAAAAAAAAAAAAAARES/9oADAMBAAIRAxEAPwBd11tLvAE0qLmcgTcjwJDtjz4y1OxRNy3PNG9d+LYjbO5X2pUpqCnsC335w11ASOAAODShdUvHjdIXVpQmD//Z",
    "alt": "Copy Of Dscf0630",
    "original": "Copy of DSCF0630.JPG",
    "category": "portraits",
    "featured": false
  },
  {
    "slug": "copy-of-dscf0687",
    "src": "/gallery/copy-of-dscf0687.jpg",
    "avif": "/gallery/copy-of-dscf0687.avif",
    "webp": "/gallery/copy-of-dscf0687.webp",
    "width": 2560,
    "height": 1707,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAeABQDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAMFBAL/xAAmEAACAgIBAwIHAAAAAAAAAAABAgADESEEBRIiQZITFCMxgZGh/8QAGAEAAwEBAAAAAAAAAAAAAAAAAAEDAgT/xAAZEQEBAQEBAQAAAAAAAAAAAAABABITAhH/2gAMAwEAAhEDEQA/AFdF7gmANMRkSpylKUMRr0krheHT3bOypM1pyRd0xhnLppv7OfaCVcfUZFWCn5MIvjt9IZhCVwhajpTpd4P2nxOj95h4vJan4wbOG125lY1U2Y7qw2BjY9P3GfL0Kuqa/bMbKuWlU8uta8Ftwm96KCxJqT24hDp5lzb/2Q==",
    "alt": "Copy Of Dscf0687",
    "original": "Copy of DSCF0687.JPG",
    "category": "portraits",
    "featured": false
  },
  {
    "slug": "copy-of-dscf0792",
    "src": "/gallery/copy-of-dscf0792.jpg",
    "avif": "/gallery/copy-of-dscf0792.avif",
    "webp": "/gallery/copy-of-dscf0792.webp",
    "width": 2560,
    "height": 1707,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAQFBv/EACAQAAICAAYDAAAAAAAAAAAAAAECAAMEBRESMVETFEH/xAAWAQEBAQAAAAAAAAAAAAAAAAADAQL/xAAYEQEBAAMAAAAAAAAAAAAAAAABAAISYf/aAAwDAQACEQMRAD8AKMK1gO0cDmMV+mg0sBY9/Isca9VXjUABhzJ9l7GXJVsYgFaNGWsdQ9Y17EJm3tbdCHr2Xbl//9k=",
    "alt": "Copy Of Dscf0792",
    "original": "Copy of DSCF0792.JPG",
    "category": "portraits",
    "featured": false
  },
  {
    "slug": "copy-of-dscf0839",
    "src": "/gallery/copy-of-dscf0839.jpg",
    "avif": "/gallery/copy-of-dscf0839.avif",
    "webp": "/gallery/copy-of-dscf0839.webp",
    "width": 2560,
    "height": 1707,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAQFAgP/xAAhEAABBAEEAwEAAAAAAAAAAAABAAIDERIEEyFBMTJhgf/EABYBAQEBAAAAAAAAAAAAAAAAAAIBA//EABcRAQEBAQAAAAAAAAAAAAAAAAEAESH/2gAMAwEAAhEDEQA/AJeofLNp9s3iDdDtZliZG0jB8bAAC/Lg89piJpGNEUPAIsLpiJNPJC8AtsvNCuln2aFL2I79gP1CcdHHGcRG2h8QrjHS/9k=",
    "alt": "Copy Of Dscf0839",
    "original": "Copy of DSCF0839.JPG",
    "category": "portraits",
    "featured": false
  },
  {
    "slug": "copy-of-hsbc-42",
    "src": "/gallery/copy-of-hsbc-42.jpg",
    "avif": "/gallery/copy-of-hsbc-42.avif",
    "webp": "/gallery/copy-of-hsbc-42.webp",
    "width": 2560,
    "height": 1709,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAABQADBv/EACEQAAIBBAEFAQAAAAAAAAAAAAECAwAEERITBSExUWHB/8QAFQEBAQAAAAAAAAAAAAAAAAAAAwH/xAAYEQADAQEAAAAAAAAAAAAAAAAAAQIRQf/aAAwDAQACEQMRAD8ANS7duNBKsgDEYVckZP7Wt0sl9PrJIW0HbQgAD39oeK4ZUVMDUdz9pJJQ16IVUKnJrjzgE0lrokU71MOuLcxMoUGRSoIYVV00nTYb4iYFoSRgqngn3VRaXGf/2Q==",
    "alt": "Copy Of Hsbc 42",
    "original": "Copy of HSBC-42.jpg",
    "category": "events",
    "featured": false
  },
  {
    "slug": "copy-of-hsbc-47",
    "src": "/gallery/copy-of-hsbc-47.jpg",
    "avif": "/gallery/copy-of-hsbc-47.avif",
    "webp": "/gallery/copy-of-hsbc-47.webp",
    "width": 2560,
    "height": 1709,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAMEAQX/xAAjEAACAQMEAwADAAAAAAAAAAABAgMAESEEEjFBBRMiUWGh/8QAFgEBAQEAAAAAAAAAAAAAAAAAAAID/8QAGREAAwEBAQAAAAAAAAAAAAAAAAECERJh/9oADAMBAAIRAxEAPwB2h1UaRLGpeNy5faRdRYdHqmzTw+z1tNu2qd6gW+Tk2zUXiNOI9csoYsqfARs5Pd63zTXD4A3NbGOCefzU0+2axKlEzeRmZidMzGM8dfyiucIrC1xgkcfuimeDD//Z",
    "alt": "Copy Of Hsbc 47",
    "original": "Copy of HSBC-47.jpg",
    "category": "events",
    "featured": false
  },
  {
    "slug": "copy-of-ey-2176",
    "src": "/gallery/copy-of-ey-2176.jpg",
    "avif": "/gallery/copy-of-ey-2176.avif",
    "webp": "/gallery/copy-of-ey-2176.webp",
    "width": 2560,
    "height": 1709,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAMBAgQF/8QAJRAAAgECBQMFAAAAAAAAAAAAAQIDABEEBRIhMRQiQSMygpGh/8QAFgEBAQEAAAAAAAAAAAAAAAAAAgAB/8QAGBEBAQEBAQAAAAAAAAAAAAAAAQARITH/2gAMAwEAAhEDEQA/AJlzrqyFgkdCBvYWD/dbMdmC4mFotYTa9iPNViwUC6LRrZR2i3FOZVPKKfiKabQh725noP3SzlSeAD4op0hUv7f2ijlu3//Z",
    "alt": "Copy Of Ey 2176",
    "original": "Copy of ey-2176.jpg",
    "category": "portraits",
    "featured": false
  },
  {
    "slug": "copy-of-ey-2395",
    "src": "/gallery/copy-of-ey-2395.jpg",
    "avif": "/gallery/copy-of-ey-2395.avif",
    "webp": "/gallery/copy-of-ey-2395.webp",
    "width": 2560,
    "height": 1709,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAMEAgX/xAAiEAABBAEEAgMAAAAAAAAAAAABAAIDERIEEyEiFVExQXH/xAAWAQEBAQAAAAAAAAAAAAAAAAAAAgP/xAAZEQADAAMAAAAAAAAAAAAAAAAAARESIXH/2gAMAwEAAhEDEQA/AOm2d7YdySNu40G74F+lqLW7gZhh2HYX8H0pNC/yGje3UC2h2NA1dFVtgjZGdsYAACvxaNTSHRL5BkbHKEqXq8/d88oU4in/2Q==",
    "alt": "Copy Of Ey 2395",
    "original": "Copy of ey-2395.jpg",
    "category": "portraits",
    "featured": false
  },
  {
    "slug": "copy-of-lng-0174",
    "src": "/gallery/copy-of-lng-0174.jpg",
    "avif": "/gallery/copy-of-lng-0174.avif",
    "webp": "/gallery/copy-of-lng-0174.webp",
    "width": 2560,
    "height": 1707,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAGAAAAgMAAAAAAAAAAAAAAAAAAAQDBQb/xAAiEAABAwQCAgMAAAAAAAAAAAACAQMRAAUSIQQxFFGR4fD/xAAXAQADAQAAAAAAAAAAAAAAAAAAAQID/8QAGBEAAwEBAAAAAAAAAAAAAAAAAAEREkH/2gAMAwEAAhEDEQA/AFeVacLakDJDjtE31uohtomxx0aA0diSRZLJYnqtG+mPFyHSyifNJ8B02wJUVJAdQkdr9Ukqw5RFm03BsIJoRncB+7oq58pz3RWuERT/2Q==",
    "alt": "Copy Of Lng 0174",
    "original": "Copy of lng-0174.jpg",
    "category": "portraits",
    "featured": false
  },
  {
    "slug": "copy-of-vjc-6566",
    "src": "/gallery/copy-of-vjc-6566.jpg",
    "avif": "/gallery/copy-of-vjc-6566.avif",
    "webp": "/gallery/copy-of-vjc-6566.webp",
    "width": 2560,
    "height": 1709,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAUBAgME/8QAIxAAAgIBAwMFAAAAAAAAAAAAAQIAAxEEEiEFQYETMUKR0f/EABcBAAMBAAAAAAAAAAAAAAAAAAABAgP/xAAYEQEAAwEAAAAAAAAAAAAAAAAAARIhUf/aAAwDAQACEQMRAD8AQPp9TbtVkZlrGxeOw7Sa6tRVcHrPpE/IHBHmPFPEo6K9iswyVyB5mNkYwo6a9ybnY2nOMsG/YTq3Ee2fuELxwsf/2Q==",
    "alt": "Copy Of Vjc 6566",
    "original": "Copy of vjc-6566.jpg",
    "category": "events",
    "featured": false
  },
  {
    "slug": "copy-of-vjc-6737",
    "src": "/gallery/copy-of-vjc-6737.jpg",
    "avif": "/gallery/copy-of-vjc-6737.avif",
    "webp": "/gallery/copy-of-vjc-6737.webp",
    "width": 2560,
    "height": 3835,
    "orientation": "portrait",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAeABQDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAMFAgT/xAAnEAEAAQMDAwIHAAAAAAAAAAABAgADEQQSIQVBUWFxExQiMYGh8P/EABYBAQEBAAAAAAAAAAAAAAAAAAIBA//EABcRAQEBAQAAAAAAAAAAAAAAAAEAESH/2gAMAwEAAhEDEQA/AOTrdhUuRFTyr37f2KjqsZPg7Vc1N0I2/i3AjJYpt5cd6nW5FldkJEmLGeeRH7PpRyCC7T4XFMuKKfDTRkZM4z4oq6WalR6o/Ly07ZNhlzt9cZK6L5u1li1C3Lau64oogODP5adKxc1EWcbm0inHty/ris3L7mUIfTNhu3Yz3o7aDzJ8LFiBiNuIe1FZJOOXmipsO3//2Q==",
    "alt": "Copy Of Vjc 6737",
    "original": "Copy of vjc-6737.jpg",
    "category": "events",
    "featured": false
  },
  {
    "slug": "dscf4177",
    "src": "/gallery/dscf4177.jpg",
    "avif": "/gallery/dscf4177.avif",
    "webp": "/gallery/dscf4177.webp",
    "width": 2560,
    "height": 1707,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAAF/8QAIRAAAgEEAgIDAAAAAAAAAAAAAQIDAAQRIRITMUEygZH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAP/EABkRAAMBAQEAAAAAAAAAAAAAAAABAhESIf/aAAwDAQACEQMRAD8Azor9JI0gcMNfIHVBtZUt7/vYA9Z5EBs5oglcRlARhd+N/tUbOY8ctHPqilvjGcQq7uoprl5EJAY5wTVQeZ9a+6qFKRdH/9k=",
    "alt": "Dscf4177",
    "original": "DSCF4177.JPG",
    "category": "portraits",
    "featured": false
  },
  {
    "slug": "dscf4178",
    "src": "/gallery/dscf4178.jpg",
    "avif": "/gallery/dscf4178.avif",
    "webp": "/gallery/dscf4178.webp",
    "width": 2560,
    "height": 1707,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAeABQDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAMFAQT/xAAlEAEAAgEDAwQDAQAAAAAAAAABAgMRAAQSBSExExRRYTJBQqH/xAAXAQEBAQEAAAAAAAAAAAAAAAACAQAD/8QAGhEAAgIDAAAAAAAAAAAAAAAAAAERURJhcf/aAAwDAQACEQMRAD8AhQ3U4bdasxtRiyHCmk20+rTt74Acn02IPZP3n7+NU+k9Ljb0x3k4SWMpduXHIeUdb7QtLYQjKlilkISfyPBg+/nU6VKhd0Pb2NdUGwAV7ecaNM3UaK9xOAoDjGCX+mjRjR0ydk3391hGmyfKoVIH8r51Q2d1kLIzjGSxAhyygfGNS9s8TGNUDc8agDSbgCRy7vql1m6ts7R5SXA+NGkTDmpCLly5NGsGD//Z",
    "alt": "Dscf4178",
    "original": "DSCF4178.JPG",
    "category": "portraits",
    "featured": false
  },
  {
    "slug": "dscf4251",
    "src": "/gallery/dscf4251.jpg",
    "avif": "/gallery/dscf4251.avif",
    "webp": "/gallery/dscf4251.webp",
    "width": 2560,
    "height": 1707,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAQFAwb/xAAhEAACAgIBBAMAAAAAAAAAAAABAgARAwUxBBIiURNBcf/EABUBAQEAAAAAAAAAAAAAAAAAAAMC/8QAFxEBAQEBAAAAAAAAAAAAAAAAAQARIf/aAAwDAQACEQMRAD8Ajasr86sxAC/VcyzudkOo4YgKAO0CKavX47QuxaqPqP8AX61GQ5BkYED9gqbKHLnGzeRFcezCY5/DM6i6BrmESi//2Q==",
    "alt": "Dscf4251",
    "original": "DSCF4251.JPG",
    "category": "portraits",
    "featured": false
  },
  {
    "slug": "dscf4266",
    "src": "/gallery/dscf4266.jpg",
    "avif": "/gallery/dscf4266.avif",
    "webp": "/gallery/dscf4266.webp",
    "width": 2560,
    "height": 1707,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAMBBAUG/8QAIRAAAgEEAgIDAAAAAAAAAAAAAQIRAAMEEgUhEzEjMkH/xAAVAQEBAAAAAAAAAAAAAAAAAAAAA//EABYRAAMAAAAAAAAAAAAAAAAAAAABEf/aAAwDAQACEQMRAD8AjjMtbADWkKwNmMT1ScrPG7HSVeYE+6bw+KO2Y7H8kdCtDJ4m38j7CSdvr6qURSs5i7ea42xVR1RV9uLSZ8jd0UqEZ//Z",
    "alt": "Dscf4266",
    "original": "DSCF4266.JPG",
    "category": "portraits",
    "featured": false
  },
  {
    "slug": "fa-10",
    "src": "/gallery/fa-10.jpg",
    "avif": "/gallery/fa-10.avif",
    "webp": "/gallery/fa-10.webp",
    "width": 2560,
    "height": 3835,
    "orientation": "portrait",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAeABQDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAMFBAb/xAAnEAACAQMDAQkBAAAAAAAAAAABAgMAERIEISIxBRRBQlFhcYGR8P/EABgBAAIDAAAAAAAAAAAAAAAAAAABAgME/8QAHBEBAAICAwEAAAAAAAAAAAAAAQACAxESIVGx/9oADAMBAAIRAxEAPwCPBoUK5SLIvytN7vAeMaux8ePStsU0thI0z4Wucj0p6ahcjd35eY3/AIUhXshcKurdMiyaM5nGwHvRVmYqX3ZD9UVEtb2HE8mTT6UFciuYI3BOxpbyiTCM3Wx3t1PpTezgw0wyO4JXY1FjmmyjkZ7gyY2/KMdtbIsqZEdTpVGljUK0UzMByIcWJopTEljRVPNmgyYPfs//2Q==",
    "alt": "Fa 10",
    "original": "FA-10.jpg",
    "category": "events",
    "featured": false
  },
  {
    "slug": "fa-2",
    "src": "/gallery/fa-2.jpg",
    "avif": "/gallery/fa-2.avif",
    "webp": "/gallery/fa-2.webp",
    "width": 2560,
    "height": 3835,
    "orientation": "portrait",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAeABQDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAMCBAUB/8QAJxAAAgEDAgUEAwAAAAAAAAAAAQIDAAQREiEFIjEzQRNxkbFSgeH/xAAXAQEBAQEAAAAAAAAAAAAAAAABAgME/8QAHhEAAgEFAAMAAAAAAAAAAAAAAAERAgMSIVETMbH/2gAMAwEAAhEDEQA/AMGG3jY91asS2EUQBaQAkZwdq7YxpqwJ1BxkePv91pXkiXDLlwsSdT+WapUabkzdyGlHsxmiiB7yfNFMa3jz3k+DRRi+/RzRem4THPEiwkDnBfwdPnFRsuHwpxK7jOfTQKUHvTFkVo9Dwo7agysxPL7VM3Eu+rTjxgb/ANrkzr6E6ga1nADt9UVTadietFHkudIk/9k=",
    "alt": "Fa 2",
    "original": "FA-2.jpg",
    "category": "events",
    "featured": false
  },
  {
    "slug": "hockey-19",
    "src": "/gallery/hockey-19.jpg",
    "avif": "/gallery/hockey-19.avif",
    "webp": "/gallery/hockey-19.webp",
    "width": 2560,
    "height": 1709,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMB/8QAHxAAAgMAAgIDAAAAAAAAAAAAAQIAAxEEEiExQWFx/8QAFgEBAQEAAAAAAAAAAAAAAAAAAQME/8QAHBEAAQQDAQAAAAAAAAAAAAAAAAECBCEDExRR/9oADAMBAAIRAxEAPwDePxqlfua9OH5wbI1cauxrA6jVbwVO7+wtzke5tO1BsJOnfM0rGZVE0kO9JWcEFyRmfcSj3N2iPPjDe8//2Q==",
    "alt": "Hockey 19",
    "original": "Hockey-19.jpg",
    "category": "sports",
    "featured": false
  },
  {
    "slug": "hockey-47",
    "src": "/gallery/hockey-47.jpg",
    "avif": "/gallery/hockey-47.avif",
    "webp": "/gallery/hockey-47.webp",
    "width": 2560,
    "height": 1709,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAECBP/EACEQAAIBBAICAwAAAAAAAAAAAAECEQADEiEEMSJBUWHh/8QAFwEAAwEAAAAAAAAAAAAAAAAAAQIDBP/EABoRAAIDAQEAAAAAAAAAAAAAAAACARRBAxP/2gAMAwEAAhEDEQA/AJ49mz26gk9kCKbKCyrbVMPI7k4nXwfulZnHZkEdRVyLYOCxOzFaqyYRjtOmVuOhPiliPWSNNFN7py/aKNZBfdj/2Q==",
    "alt": "Hockey 47",
    "original": "Hockey-47.jpg",
    "category": "sports",
    "featured": true
  },
  {
    "slug": "vinexpo-61",
    "src": "/gallery/vinexpo-61.jpg",
    "avif": "/gallery/vinexpo-61.avif",
    "webp": "/gallery/vinexpo-61.webp",
    "width": 2560,
    "height": 1709,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAQFAQP/xAAhEAACAQQCAgMAAAAAAAAAAAABAgMABBESBSExkSIycf/EABUBAQEAAAAAAAAAAAAAAAAAAAIB/8QAFhEBAQEAAAAAAAAAAAAAAAAAABEB/9oADAMBAAIRAxEAPwDYOQiS4EBRHCLl3J7f8pyO4jkuysSAon2PfRqC1jGlqbiIlBqcp5B7qpxbb2QLDO65PsijDMvFaztuQPeKK5H4YVfAFFWYN1//2Q==",
    "alt": "Vinexpo 61",
    "original": "Vinexpo-61.jpg",
    "category": "events",
    "featured": false
  },
  {
    "slug": "violet-153",
    "src": "/gallery/violet-153.jpg",
    "avif": "/gallery/violet-153.avif",
    "webp": "/gallery/violet-153.webp",
    "width": 2560,
    "height": 1707,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAQFAgP/xAAhEAACAQUAAQUAAAAAAAAAAAABAgMABBESIWEUMkFRcf/EABYBAQEBAAAAAAAAAAAAAAAAAAEDBP/EABgRAAMBAQAAAAAAAAAAAAAAAAABAhIR/9oADAMBAAIRAxEAPwBCNGg3lMxKsDjBOfHPuu8E5c+mvAXg16yjB1pt7VJI9SSB45WVsoyxYs5OMe6pbaZpz0lXFnFFO4jZzETlPyiqJjEZ1BJx8npoodApP//Z",
    "alt": "Violet 153",
    "original": "Violet-153.jpg",
    "category": "portraits",
    "featured": false
  },
  {
    "slug": "violet-90",
    "src": "/gallery/violet-90.jpg",
    "avif": "/gallery/violet-90.avif",
    "webp": "/gallery/violet-90.webp",
    "width": 2560,
    "height": 1707,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAUGBP/EACEQAAICAQQCAwAAAAAAAAAAAAECAxEABAUhMRIkMkHw/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgP/xAAYEQEAAwEAAAAAAAAAAAAAAAAAERIxQf/aAAwDAQACEQMRAD8Az7X6yzSRj5KSbcKV5PQxjtwVYZ5pHLnUOWIfk/u8jVVolSVWFsaqsptsYqIkbxYNGW6qiMMwrvFHDOohQdUKwxKdU30owxXGj//Z",
    "alt": "Violet 90",
    "original": "Violet-90.jpg",
    "category": "portraits",
    "featured": true
  },
  {
    "slug": "a-8382",
    "src": "/gallery/a-8382.jpg",
    "avif": "/gallery/a-8382.avif",
    "webp": "/gallery/a-8382.webp",
    "width": 2560,
    "height": 1709,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAQFAv/EACIQAAIBBAIBBQAAAAAAAAAAAAECAwAEERIFMSEiQUJxof/EABUBAQEAAAAAAAAAAAAAAAAAAAME/8QAGREAAwEBAQAAAAAAAAAAAAAAAAERAiED/9oADAMBAAIRAxEAPwCxz3JC0gjSIuru2SU7Cjz+9UtIJrqe3mklbXsfEqMA+RUe7vnlSJnVW2Xb1ZODTcPKSXVnGrou5GC1HWyxeazlMdkggWRlkuI8g+NlXJHfv90VhuMglw0wEjY7IoplJ0i1bxn/2Q==",
    "alt": "A 8382",
    "original": "a-8382.jpg",
    "category": "portraits",
    "featured": false
  },
  {
    "slug": "a-8762",
    "src": "/gallery/a-8762.jpg",
    "avif": "/gallery/a-8762.avif",
    "webp": "/gallery/a-8762.webp",
    "width": 2560,
    "height": 1709,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAEDAgX/xAAgEAACAQQCAwEAAAAAAAAAAAABAgMABBEhBRIxQWGR/8QAFgEBAQEAAAAAAAAAAAAAAAAAAQAD/8QAGBEAAwEBAAAAAAAAAAAAAAAAAAESESH/2gAMAwEAAhEDEQA/AKWfJM/HCEsQuMd+2xvPit3l1LLCDchSA3eJsEFflLilBsoDsHG+us7qnNXDR8dIsYC4TRHreKDVtVo4+UnMalYVYEeWk6n8org2xLwq8h7sfZoqvOBKfT//2Q==",
    "alt": "A 8762",
    "original": "a-8762.jpg",
    "category": "portraits",
    "featured": false
  },
  {
    "slug": "anselm-4364",
    "src": "/gallery/anselm-4364.jpg",
    "avif": "/gallery/anselm-4364.avif",
    "webp": "/gallery/anselm-4364.webp",
    "width": 2560,
    "height": 1709,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAGAAAAgMAAAAAAAAAAAAAAAAAAAYDBAX/xAAkEAABBAEDAwUAAAAAAAAAAAABAAIDEQQSEyEUMUEFBjJhwf/EABYBAQEBAAAAAAAAAAAAAAAAAAIBA//EABcRAQEBAQAAAAAAAAAAAAAAAAEAEgL/2gAMAwEAAhEDEQA/AMFvoz9Er5pNtrGFzbF6iPH0qLMd0hIjFkCzzynKIdbh7MxOlwq28GlDH7XxAWO3Zr+XcD8QG1eSV+jyXAEQvIrhCcZsDGa+hGe3goR01wX/2Q==",
    "alt": "Anselm 4364",
    "original": "anselm-4364.jpg",
    "category": "portraits",
    "featured": false
  },
  {
    "slug": "edited-49",
    "src": "/gallery/edited-49.jpg",
    "avif": "/gallery/edited-49.avif",
    "webp": "/gallery/edited-49.webp",
    "width": 2560,
    "height": 1709,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwAC/8QAHhAAAgMAAgMBAAAAAAAAAAAAAQIAAxESIRMxQdH/xAAWAQEBAQAAAAAAAAAAAAAAAAADAAH/xAAaEQACAwEBAAAAAAAAAAAAAAAAAQITURRB/9oADAMBAAIRAxEAPwAKqKvAMtPJdOYe5pQGrR0dMI3tex+wKbmC58iNZgGD16jc0dC6ZLxAW0U+RiyVMSdJxpQrLTylKiOsy+WI/9k=",
    "alt": "Edited 49",
    "original": "edited-49.jpg",
    "category": "portraits",
    "featured": false
  },
  {
    "slug": "ey-2368",
    "src": "/gallery/ey-2368.jpg",
    "avif": "/gallery/ey-2368.avif",
    "webp": "/gallery/ey-2368.webp",
    "width": 2560,
    "height": 1709,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAIDBP/EACEQAAIBBAICAwAAAAAAAAAAAAECEQADBBIhMRNxQVGx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgD/xAAaEQEBAAIDAAAAAAAAAAAAAAABAAIhERIx/9oADAMBAAIRAxEAPwCtx8i3k3N0YWWhLcdRE9e6sbOpTcQdZk/lbX1yWt+RZG0RNNexxBYsSy8g0908PtFmIjn4opCx49fVFLosHMNX/9k=",
    "alt": "Ey 2368",
    "original": "ey-2368.jpg",
    "category": "events",
    "featured": true
  },
  {
    "slug": "g-d-100",
    "src": "/gallery/g-d-100.jpg",
    "avif": "/gallery/g-d-100.avif",
    "webp": "/gallery/g-d-100.webp",
    "width": 2560,
    "height": 1709,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAQFAwb/xAAiEAABAwQCAgMAAAAAAAAAAAABAgMRAAQhMQUSE0EGcaH/xAAWAQEBAQAAAAAAAAAAAAAAAAABAgT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABED/9oADAMBAAIRAxEAPwBHj0C75Psy2khYKh3GIjf5VcWjxQ8fEwktYII3icVyLV/dWzJLL6klzBPvGs1oOXvk+NxL6uwUZHoxGxWg7IYU5VBxDt/NwlsBK9QoJx9UUgr5FyBMpcSmdgIG6KHqrsgX/9k=",
    "alt": "G D 100",
    "original": "g+d-100.jpg",
    "category": "weddings",
    "featured": false
  },
  {
    "slug": "g-d-104",
    "src": "/gallery/g-d-104.jpg",
    "avif": "/gallery/g-d-104.avif",
    "webp": "/gallery/g-d-104.webp",
    "width": 2560,
    "height": 1709,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAIGAwX/xAAgEAACAgICAgMAAAAAAAAAAAABAgMRAAQSIRQiMVFx/8QAFwEAAwEAAAAAAAAAAAAAAAAAAQIDBP/EABkRAAIDAQAAAAAAAAAAAAAAAAABAgMRIf/aAAwDAQACEQMRAD8ASfaO1JDBrTu7336i6/T1me5r7RguGSVjxJ7UfAziyaqpGWRitCsWpVa/IkIJFjke8tCzFmAaKTx11FWN4lJK8rJBJv7wyZnkZ5LZiTVd4ZqjZzojR//Z",
    "alt": "G D 104",
    "original": "g+d-104.jpg",
    "category": "weddings",
    "featured": false
  },
  {
    "slug": "g-d-57",
    "src": "/gallery/g-d-57.jpg",
    "avif": "/gallery/g-d-57.avif",
    "webp": "/gallery/g-d-57.webp",
    "width": 2560,
    "height": 1709,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAQFAgP/xAAkEAACAQMDAwUAAAAAAAAAAAABAgMAERIEIUEFImETFBVCof/EABYBAQEBAAAAAAAAAAAAAAAAAAECA//EABkRAQADAQEAAAAAAAAAAAAAAAEAAhESIf/aAAwDAQACEQMRAD8AXGoERWOZWjkIBxYWO9dDqjHdo2jLFMgC315I8051PH4x3ZFfAIy5C9u4VvU9E0bMrBMRHEXEa7KfB5/a0vp5JoljWSNR1b2spjEPr37i+I54oqJIWaRtwLG1gNqKOmOE/9k=",
    "alt": "G D 57",
    "original": "g+d-57.jpg",
    "category": "weddings",
    "featured": true
  },
  {
    "slug": "sun-7458",
    "src": "/gallery/sun-7458.jpg",
    "avif": "/gallery/sun-7458.avif",
    "webp": "/gallery/sun-7458.webp",
    "width": 2560,
    "height": 1709,
    "orientation": "landscape",
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABQDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAQFAgP/xAAhEAACAgICAwADAAAAAAAAAAABAgMRABIEIQUxQSJRcf/EABYBAQEBAAAAAAAAAAAAAAAAAAABAv/EABoRAAEFAQAAAAAAAAAAAAAAAAABERIhUUH/2gAMAwEAAhEDEQA/AJE/FjSGO+QquzbOde/Vjv72MzPAoGxlRn2FAC7se/3j/mO4oKC2ZNbYX8OcuUVXyXDiCUHC7G+z36/mIiuibwN+IIUkLWGV5+OokOpoHuqwzDLhLw//2Q==",
    "alt": "Sun 7458",
    "original": "sun-7458.jpg",
    "category": "events",
    "featured": false
  }
];

export const videos: VideoClip[] = [
  {
    "slug": "008",
    "title": "Reel 008",
    "clip": "/clips/008.mp4",
    "poster": "/clips/008-poster.jpg",
    "width": 1920,
    "height": 1080,
    "orientation": "landscape",
    "original": "008.mp4"
  },
  {
    "slug": "012",
    "title": "Reel 012",
    "clip": "/clips/012.mp4",
    "poster": "/clips/012-poster.jpg",
    "width": 1920,
    "height": 1080,
    "orientation": "landscape",
    "original": "012.mp4"
  },
  {
    "slug": "015",
    "title": "Reel 015",
    "clip": "/clips/015.mp4",
    "poster": "/clips/015-poster.jpg",
    "width": 1920,
    "height": 1080,
    "orientation": "landscape",
    "original": "015.mp4"
  },
  {
    "slug": "016",
    "title": "Reel 016",
    "clip": "/clips/016.mp4",
    "poster": "/clips/016-poster.jpg",
    "width": 1920,
    "height": 1080,
    "orientation": "landscape",
    "original": "016.mp4"
  },
  {
    "slug": "018",
    "title": "Reel 018",
    "clip": "/clips/018.mp4",
    "poster": "/clips/018-poster.jpg",
    "width": 1920,
    "height": 1012,
    "orientation": "landscape",
    "original": "018.mp4"
  },
  {
    "slug": "019",
    "title": "Reel 019",
    "clip": "/clips/019.mp4",
    "poster": "/clips/019-poster.jpg",
    "width": 1920,
    "height": 1012,
    "orientation": "landscape",
    "original": "019.mp4"
  },
  {
    "slug": "ukc-2022-video-d2",
    "title": "UKC 2022",
    "clip": "/clips/ukc-2022-video-d2.mp4",
    "poster": "/clips/ukc-2022-video-d2-poster.jpg",
    "width": 1920,
    "height": 1080,
    "orientation": "landscape",
    "original": "UKC 2022 Video D2.mp4"
  },
  {
    "slug": "legacy-cropped",
    "title": "Legacy",
    "clip": "/clips/legacy-cropped.mp4",
    "poster": "/clips/legacy-cropped-poster.jpg",
    "width": 1280,
    "height": 720,
    "orientation": "landscape",
    "original": "legacy_cropped.mp4"
  }
];

export const featuredPhotos = photos.filter((p) => p.featured);
