import { type Testimonial } from "./feedback-schema";

/**
 * Photography reviews carried over from Carousell (carousell.sg/u/selmm),
 * newest first. Reviews for items sold are left out. Carousell only shows
 * relative ages ("4 years ago"), so dates are just the year.
 */
export const carousellTestimonials: Testimonial[] = [
  {
    id: "carousell-teresacheong-sg",
    name: "teresacheong.sg",
    shootType: "Corporate",
    rating: 5,
    message: "Engaged Anselm for his photography service to cover our Corporate Event and Official Company Opening Event. He is professional, reliable and the photos shots at our event are very well taken and well received by our VIP guests and our management. Anselm is friendly, fast and able to meet our high expectations. Highly recommended photographer to cover corporate and company events.",
    date: "2023",
    source: "carousell",
  },
  {
    id: "carousell-grauk",
    name: "grauk",
    shootType: "Birthday",
    rating: 5,
    message: "Thank you for the great photos for my daughters birthday party and will become part of our fond memories forever!",
    date: "2022",
    source: "carousell",
  },
  {
    id: "carousell-phs19",
    name: "phs19",
    shootType: "Birthday",
    rating: 5,
    message: "This was a last minute assignment and Selm carried off so well! He connected with me promptly, offered some advises and also took great pictures most importantly. Many photos turned out just the way I imagined; natural, candid and caught that ‘moment’ for my son’s first experience of party on his 7th birthday. Highly recommend for his flexibility and skill!",
    date: "2022",
    source: "carousell",
  },
  {
    id: "carousell-beyond_closet",
    name: "beyond_closet",
    shootType: "Event",
    rating: 5,
    message: "Having Anselm as our event photographer was a great decision. The pictures were well taken and capture the essence of many moments in the event. We truly appreciate your hard work and for preserving such wonderful memories for us. Thank you.",
    date: "2022",
    source: "carousell",
  },
  {
    id: "carousell-devaguru",
    name: "devaguru",
    shootType: "Event",
    rating: 5,
    message: "Anselm is very punctual. He captured the beautiful moments during the party.",
    date: "2022",
    source: "carousell",
  },
  {
    id: "carousell-stefan88",
    name: "stefan88",
    shootType: "Event",
    rating: 5,
    message: "Very friendly and responsive young man . Responsible and goes extra mile in his work. Highly recommended. Will use his services again",
    date: "2022",
    source: "carousell",
  },
  {
    id: "carousell-jej-closet",
    name: "JEJ.closet",
    shootType: "Event",
    rating: 5,
    message: "Responsive, accommodating and photos turned out great!! Will hire again if I have other events!!",
    date: "2022",
    source: "carousell",
  },
  {
    id: "carousell-iambadbatz",
    name: "iambadbatz",
    shootType: "Event",
    rating: 5,
    message: "Very quick to respond! On time and responsible photographer. Able to capture photos in an event without being in the way. Very quick to edit and produce the photos as well!",
    date: "2022",
    source: "carousell",
  },
  {
    id: "carousell-aadesh-raja",
    name: "aadesh.raja",
    shootType: "Sports",
    rating: 5,
    message: "Anselm was a friendly and very welcoming photographer. He was quite good at his skills and all my photos and video at my event was very good and satisfied. Definitely I recommend him for sports event and will work with him in my future events too.",
    date: "2022",
    source: "carousell",
  },
  {
    id: "carousell-ddpipte-ltd",
    name: "ddpipte.ltd.",
    shootType: "Event",
    rating: 5,
    message: "Most affordable and decent photography. Highly recommend 👍🏿",
    date: "2021",
    source: "carousell",
  },
  {
    id: "carousell-golden-jennis",
    name: "golden.jennis",
    shootType: "Family",
    rating: 5,
    message: "Have engaged them for our anniversary party and he captured our memories so special and edited photos were very nice Patient with our kids Wonderful pictures and have edited extra pictures as well Thank you so much",
    date: "2021",
    source: "carousell",
  },
  {
    id: "carousell-arista27",
    name: "arista27",
    shootType: "Videography",
    rating: 5,
    message: "I would highly recommend Anselm ,and cannot thank him enough even just the last minute of requesting him for making video for my daughter. He is so kind, have patience , easy to communicate and recommend me me which song is best for the video. He is soooo friendly, professional and easy going.. Thanks so much again for your hard work, 5 stars is not enough x",
    date: "2021",
    source: "carousell",
  },
  {
    id: "carousell-softwaresg",
    name: "softwaresg",
    shootType: "Event",
    rating: 5,
    message: "Very hardworking photographer.. very patient... very smooth.. hope u become more successful..👍👍",
    date: "2021",
    source: "carousell",
  },
  {
    id: "carousell-nats_about_me",
    name: "nats_about_me",
    shootType: "Event",
    rating: 5,
    message: "Photographer is really friendly and amazing. Reasonably priced and the work he did was not a disappointment. I would definitely contact him again for future events.",
    date: "2019",
    source: "carousell",
  },
  {
    id: "carousell-deerpanteth",
    name: "deerpanteth",
    shootType: "Wedding",
    rating: 5,
    message: "Engaged Anselm for our solemnization n dinner reception on 31 Dec. Very responsive, responsible n has great initiative. Our photos came out beautiful as expected with many beautiful candid shots. The team did a great n wonderful job! Thumbs up!!!",
    date: "2019",
    source: "carousell",
  },
  {
    id: "carousell-tizzdale27",
    name: "tizzdale27",
    shootType: "Birthday",
    rating: 5,
    message: "Very responsive and photos turned out to be awesome! He was able to capture the moments on my daughter’s 3rd birthday. Will definitely engage again whenever there is a chance. Goodluck and happy photo taking!",
    date: "2019",
    source: "carousell",
  },
  {
    id: "carousell-radhiqal",
    name: "radhiqal.",
    shootType: "Portraits",
    rating: 5,
    message: "Hired 1.5hrs of photography + short video montage. Friendly photographer so posing was natural. Great photos, excellent and fast service! Highly recommend!",
    date: "2019",
    source: "carousell",
  },
  {
    id: "carousell-freestyler1688",
    name: "freestyler1688",
    shootType: "Event",
    rating: 5,
    message: "Thanks for the photos !",
    date: "2019",
    source: "carousell",
  },
  {
    id: "carousell-ardenz",
    name: "ardenz",
    shootType: "Event",
    rating: 5,
    message: "Great service and good pictures. Fast turnaround time too. Will definitely engage again for other events!",
    date: "2019",
    source: "carousell",
  },
  {
    id: "carousell-girlnextdoor00",
    name: "girlnextdoor00",
    shootType: "Event",
    rating: 5,
    message: "A very professional and efficient service. He is definitely very good at what he's at. Young but very very good eye for details. The photos turned out better than expected. Will definitely engage his services again. Thumbs up",
    date: "2019",
    source: "carousell",
  },
  {
    id: "carousell-ranee2512",
    name: "ranee2512",
    shootType: "Event",
    rating: 5,
    message: "Picture was excellent. Great communication with the dealer and happy with his service. Surely will engage with him again.",
    date: "2019",
    source: "carousell",
  },
  {
    id: "carousell-baobao90",
    name: "baobao90",
    shootType: "Corporate",
    rating: 5,
    message: "Selmm aka Ansen, was professional for his age and showed a lot of dedication and passion in photography. Shots were clear enough for my organization use and record. Thank you!",
    date: "2019",
    source: "carousell",
  },
  {
    id: "carousell-calmbear_7fe41b",
    name: "calmbear_7fe41b",
    shootType: "Event",
    rating: 5,
    message: "Anselm was a very responsible and accommodative photographer. He understood the expectations of the event well. He arrived early to the venue for site recee before the start of the programme. Photos captured was clear, natural, and the smiles captured on guests and children was wonderful! Photographs were also delivered fast after a few days of the event! Thumbs up!",
    date: "2019",
    source: "carousell",
  },
  {
    id: "carousell-armidamosquitern",
    name: "armidamosquitern",
    shootType: "Event",
    rating: 5,
    message: "Very good Photographer 👍..kind and patience. 👍😊",
    date: "2019",
    source: "carousell",
  },
];

export const CAROUSELL_PROFILE_URL = "https://www.carousell.sg/u/selmm/?tab=reviews";
