/**
 * Merge the image + video manifests into a typed src/lib/media.ts data layer.
 * Applies a best-guess category taxonomy from filename prefixes (review/edit later).
 *
 * Run after optimize-images + optimize-videos: bun run scripts/generate-media.mjs
 */
import { readFile, writeFile } from "node:fs/promises";

// Best-guess category from the original filename. Edit assignments in media.ts later.
function categorize(original) {
  const n = original.toLowerCase();
  if (/^g\+?d|wedding|engage/.test(n)) return "weddings";
  if (/hockey|ukc|sport/.test(n)) return "sports";
  if (/hsbc|^ey-|vinexpo|vjc|^fa-|^sun-|^lng-|event/.test(n)) return "events";
  if (/anselm|andi|violet|portrait|^a-/.test(n)) return "portraits";
  return "portraits"; // DSCF/edited/misc default
}

// Featured = a curated hero set across categories (tweak after review).
const FEATURED = new Set([
  "anselm-0673", "anselm-0440", "g-d-57", "violet-90",
  "hockey-47", "ey-2368", "andi-13",
]);

async function readJson(p, fallback) {
  try {
    return JSON.parse(await readFile(p, "utf8"));
  } catch {
    return fallback;
  }
}

async function main() {
  const images = await readJson("scripts/.image-manifest.json", []);
  const videos = await readJson("scripts/.video-manifest.json", []);

  const photos = images.map((im) => ({
    ...im,
    category: categorize(im.original),
    featured: FEATURED.has(im.slug),
  }));

  const ts = `// AUTO-GENERATED by scripts/generate-media.mjs — do not edit by hand.
// Re-run \`bun run optimize\` to regenerate from public/images + public/videos.

export type Category = "portraits" | "weddings" | "events" | "sports";

export interface Photo {
  slug: string;
  src: string;
  avif: string;
  webp: string;
  width: number;
  height: number;
  orientation: "landscape" | "portrait";
  blurDataURL: string;
  alt: string;
  category: Category;
  featured: boolean;
  original: string;
}

export interface VideoClip {
  slug: string;
  title: string;
  clip: string;
  poster: string;
  width: number;
  height: number;
  orientation: "landscape" | "portrait";
  original: string;
}

export const categories: { id: Category; label: string }[] = [
  { id: "portraits", label: "Portraits" },
  { id: "weddings", label: "Weddings" },
  { id: "events", label: "Events" },
  { id: "sports", label: "Sports" },
];

export const photos: Photo[] = ${JSON.stringify(photos, null, 2)};

export const videos: VideoClip[] = ${JSON.stringify(videos, null, 2)};

export const featuredPhotos = photos.filter((p) => p.featured);
`;

  await writeFile("src/lib/media.ts", ts);
  console.log(
    `Wrote src/lib/media.ts — ${photos.length} photos, ${videos.length} clips`
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
